# Generated by Django 4.2.4 on 2023-09-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
