# Generated by Django 4.2.4 on 2023-09-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='genre',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Science Fiction', 'Science Fiction'), ('Romance', 'Romance')], max_length=50),
        ),
    ]
