# Generated by Django 4.2.4 on 2023-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookmodel_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='auther_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='auther_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='auther_uz',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='bio_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='title_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='title_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='title_uz',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
