# Generated by Django 4.2.4 on 2023-09-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('date_of_brth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=50)),
                ('Date_of_death', models.DateField()),
                ('Place_of_death', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='images/')),
                ('bio', models.TextField()),
                ('genre', models.CharField(choices=[('toshkent', 'toshkent'), ('Jizzax', 'Jizzax'), ('samarqand', 'samarqand')], max_length=50)),
            ],
            options={
                'db_table': 'auther',
            },
        ),
    ]
