# Generated by Django 4.2.4 on 2023-09-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0002_alter_authermodel_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authermodel',
            name='Date_of_death',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='authermodel',
            name='Place_of_death',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='authermodel',
            name='date_of_brth',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='authermodel',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='authermodel',
            name='place_of_birth',
            field=models.CharField(default='', max_length=50),
        ),
    ]
