# Generated by Django 4.2.4 on 2023-09-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0003_alter_authermodel_date_of_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authermodel',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
