# Generated by Django 4.2.4 on 2023-09-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0010_autherbookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='authermodel',
            name='Place_of_death_en',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='Place_of_death_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='Place_of_death_uz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='bio_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='first_name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='first_name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='first_name_uz',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='last_name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='last_name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='last_name_uz',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='place_of_birth_en',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='place_of_birth_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authermodel',
            name='place_of_birth_uz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
