# Generated by Django 4.2.4 on 2023-09-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0011_authermodel_place_of_death_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autherbookmodel',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='autherbookmodel',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='autherbookmodel',
            name='bio_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='autherbookmodel',
            name='name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='autherbookmodel',
            name='name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='autherbookmodel',
            name='name_uz',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
